TRUNCATE TABLE `ss_expenses`;
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('2', 'Home', '1', '1', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('3', 'Bond Repayments', '1', '1', '2');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('4', 'Utilities', '1', '4', '2');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('5', 'Security', '1', '5', '2');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('6', 'Media & comms', '1', '3', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('7', 'Maintenance', '1', '6', '2');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('8', 'Garden service', '1', '7', '2');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('10', 'Household Insurance', '1', '8', '2');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('11', 'Telephones', '1', '1', '6');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('12', 'Cellphones', '1', '2', '6');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('13', 'Internet', '1', '3', '6');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('14', 'Satellite TV', '1', '4', '6');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('15', 'TV License', '1', '5', '6');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('16', 'Dependants', '1', '4', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('17', 'Recreation', '1', '5', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('18', 'Pets', '1', '6', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('19', 'Medical', '1', '7', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('20', 'Transportation', '1', '8', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('21', 'Household Expenses', '1', '9', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('22', 'Financial planning', '1', '10', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('23', 'Annual fees/Monthly costs', '1', '11', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('24', 'Education', '1', '1', '16');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('25', 'Sports & recreation', '1', '2', '16');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('26', 'Clothing', '1', '4', '16');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('27', 'Transport', '1', '6', '16');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('28', 'Day care / Child minder', '1', '7', '16');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('29', 'Toiletries', '1', '5', '16');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('30', 'Inclusive Maintenance Costs', '1', '8', '16');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('31', 'Restaurant ', '1', '1', '17');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('32', 'Movies', '1', '2', '17');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('33', 'Gym', '1', '4', '17');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('34', 'Sports', '1', '5', '17');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('35', 'Home entertainment', '1', '6', '17');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('36', 'Books / Magazines', '1', '7', '17');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('37', 'Food', '1', '1', '18');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('38', 'Vet', '1', '2', '18');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('39', 'Training', '1', '3', '18');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('40', 'Kennels / stabling', '1', '4', '18');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('41', 'Medical aid', '1', '1', '19');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('42', 'Prescriptions', '1', '2', '19');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('43', 'Over the counter', '1', '3', '19');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('44', 'Co payments', '1', '4', '19');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('45', 'Other', '1', '5', '19');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('46', 'Car payments', '1', '1', '20');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('47', 'Petrol', '1', '2', '20');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('48', 'Motor Insurance', '1', '3', '20');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('49', 'Parking', '1', '4', '20');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('50', 'Maintenance / Cleaning', '1', '5', '20');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('51', 'Fares', '1', '6', '20');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('52', 'Groceries', '1', '1', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('53', 'Credit card', '1', '3', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('54', 'Religious Org.', '1', '4', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('55', 'Charity', '1', '5', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('56', 'Laundry / Dry cleaning', '1', '6', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('57', 'Salon grooming', '1', '7', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('58', 'Clothing', '1', '8', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('59', 'Other', '1', '11', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('60', 'Retirement', '1', '2', '22');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('61', 'Loss of Income', '1', '4', '22');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('62', 'Education Planning', '1', '6', '22');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('63', 'Bank Savings', '1', '7', '22');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('64', 'Other', '1', '8', '22');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('65', 'Vehicle licenses', '1', '1', '23');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('66', 'Media licenses', '1', '2', '23');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('67', 'Sports club', '1', '3', '23');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('68', 'Subscriptions', '1', '4', '23');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('70', 'Travel / vacations', '1', '5', '23');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('71', 'Estimated tax', '1', '2', '0');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('72', 'Client', '1', '1', '71');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('73', 'Spouse', '1', '2', '71');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('74', 'Investment Property Bond', '1', '2', '2');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('75', 'Domestic Cleaning', '1', '2', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('76', 'Bank Charges ', '1', '10', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('77', 'Gifts', '1', '9', '21');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('78', 'Spouse Retirement', '1', '3', '22');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('79', 'Spouse Loss of Income', '1', '5', '22');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('80', 'Exchange Traded Funds', '1', '1', '22');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('81', 'Cell Phone and Media', '1', '3', '16');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('82', 'Theater', '1', '3', '17');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('83', 'Rent Payment', '1', '3', '2');
INSERT INTO `ss_expenses` (`expenseid`, `expensename`, `expensestatus`, `expenseorder`, `parentid`) VALUES ('84', 'News', '1', '8', '17');
